controller_manager:
  ros__parameters:
    update_rate: 50

    arm_joints_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_joints_controller:
  ros__parameters:
    publish_rate: 50.0
    joints: ["joint_1", "joint_2", "joint_3", "joint_4"]
    interface_name: "position"